### ISSUE TITLE
Trying to upload an empty dir should probably be an error

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Platform/anaconda-project#11]
See https://github.com/ContinuumIO/navigator/issues/944#issuecomment-283706779

**Comment by havocp** [comment]
My plan is to handle this in the same way as a broken anaconda-project.yml (project.problems will have an error with an auto-fix, so on the command line it will say "no anaconda-project.yml do you want to create one?" or something like that). The auto-fix will be equivalent to `anaconda-project init` perhaps.

**Comment by goanpeca** [comment]
Next iteration of Navi will add support for handling autofixes in the problems dialog so this sounds good :-)

**Comment by havocp** [comment]
My plan doesn't work, it gets bogged down in a circular mess because the way we create a fresh anaconda-project.yml involves fixing the problems list. I'll just add a special case in upload that changes to the Project have to be saved first.
