### ISSUE TITLE
Fix failing tests with conda-canary

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Platform/anaconda-project#126]
- [ ] `anaconda_project/internal/cli/test/test_activate.py::test_activate`
 - [ ] `anaconda_project/internal/cli/test/test_activate.py::test_activate_quoting`
 - [ ] `anaconda_project/internal/cli/test/test_activate.py::test_main`
 - [ ] `anaconda_project/internal/cli/test/test_activate.py::test_main_dirname_not_provided_use_pwd`
 - [ ] `anaconda_project/internal/cli/test/test_activate.py::test_main_dirname_provided_use_it`
 - [ ] `anaconda_project/internal/cli/test/test_activate.py::test_main_fails_to_redis`
 - [ ] `anaconda_project/internal/cli/test/test_clean.py::test_clean_command_on_empty_project`
 - [ ] `anaconda_project/internal/cli/test/test_download_commands.py::test_remove_download`
 - [ ] `anaconda_project/internal/cli/test/test_download_commands.py::test_remove_download_dir`
 - [ ] `anaconda_project/internal/cli/test/test_download_commands.py::test_remove_download_directory_error`
 - [ ] `anaconda_project/internal/cli/test/test_download_commands.py::test_remove_download_file_error`
 - [ ] `anaconda_project/internal/cli/test/test_download_commands.py::test_remove_download_missing_var`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_ask_variables_interactively`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_ask_variables_interactively_empty_answer_re_asks`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_ask_variables_interactively_eof_answer_gives_up`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_ask_variables_interactively_then_set_variable_fails`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_ask_variables_interactively_whitespace_answer_re_asks`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_display_suggestions`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_main_fails_to_redis`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_no_ask_variables_interactively_not_interactive`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_prepare_command_assume_no`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_prepare_command_choose_command_chooses_env_spec`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_prepare_command_choose_environment`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_prepare_command_development`
 - [ ] `anaconda_project/internal/cli/test/test_prepare.py::test_prepare_command_production`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_main`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_main_dirname_not_provided_use_pwd`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_main_failed_exec`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_executable_not_in_config`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_extra_args`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_extra_args_with_double_hyphen`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_failed_prepare`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_no_app_entry`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_nonexistent_name`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_omit_name_use_default`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_specify_name_after_options`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_specify_name_before_options`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_command_verbose`
 - [ ] `anaconda_project/internal/cli/test/test_run.py::test_run_notebook_not_in_config`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service_by_type`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service_duplicate`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service_missing_variable`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service_running_redis`
 - [ ] `anaconda_project/internal/cli/test/test_service_commands.py::test_remove_service_shutdown_fails`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_conda_create_and_install_and_remove`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_conda_create_bad_package`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_conda_info`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_conda_install_no_packages`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_conda_remove_no_packages`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_environ_set_prefix_to_root`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_msys_for_all_platforms`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_resolve_dependencies_for_bogus_package_with_actual_conda`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_resolve_dependencies_with_actual_conda_current_platform`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_resolve_dependencies_with_actual_conda_depending_on_conda`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_resolve_dependencies_with_actual_conda_other_platforms`
 - [ ] `anaconda_project/internal/test/test_conda_api.py::test_resolve_root_prefix`
 - [ ] `anaconda_project/internal/test/test_default_conda_manager.py::test_conda_create_and_install_and_remove`
 - [ ] `anaconda_project/internal/test/test_default_conda_manager.py::test_resolve_dependencies_with_actual_conda`
 - [ ] `anaconda_project/internal/test/test_default_conda_manager.py::test_timestamp_file_works`
 - [ ] `anaconda_project/internal/test/test_pip_api.py::test_conda_create_and_install_and_remove_pip_stuff`
 - [ ] `anaconda_project/internal/test/test_pip_api.py::test_pip_errors`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_bootstrap_env.py::test_prepare_and_unprepare_project_scoped_env`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_bootstrap_env.py::test_prepare_project_scoped_env_not_attempted_in_check_mode`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_bootstrap_env.py::test_prepare_project_scoped_env_with_packages`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_env.py::test_prepare_and_unprepare_project_scoped_env`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_env.py::test_prepare_project_scoped_env_not_attempted_in_check_mode`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_env.py::test_prepare_project_scoped_env_with_packages`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_conda_env.py::test_unprepare_gets_error_on_delete`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_configure`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_failed_download`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_failed_download_before_connect`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_file_exists`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_and_unprepare_download`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_exception`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_mismatched_checksum_after_download`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_of_broken_zip_file`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_of_zip_file`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_of_zip_file_checksum`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_of_zip_file_no_unzip`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_prepare_download_of_zip_file_no_zip_extension`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_provide_minimal`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_provide_no_download_in_check_mode`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_download_provider.py::test_unprepare_download_fails`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_do_not_start_local_redis_server_in_check_mode`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_do_not_start_local_redis_server_in_prod_mode`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_exec_fails`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_exec_fails_logfile_is_dir`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_exec_fails_no_logfile`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_no_port_available`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_not_on_path`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_fail_to_prepare_local_redis_server_scope_system`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_and_unprepare_local_redis_server`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_and_unprepare_local_redis_server_with_failed_unprovide`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_and_unprepare_two_local_redis_servers_with_failed_unprovide`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_local_redis_server_times_out`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_local_redis_server_twice_reuses`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_prepare_redis_url_with_dict_in_variables_section`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_redis_server_configure_custom_port_range`
 - [ ] `anaconda_project/requirements_registry/providers/test/test_redis_provider.py::test_set_scope_in_local_state`
 - [ ] `anaconda_project/requirements_registry/test/test_provider.py::test_env_var_provider_prepare_unprepare`
 - [ ] `anaconda_project/test/test_plugins.py::test_prepare_plugin_command`
 - [ ] `anaconda_project/test/test_prepare.py::test_default_to_system_environ`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_choose_command`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_choose_environment`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_command_not_in_project`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_empty_directory`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_some_env_var_already_set`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_some_env_var_not_set`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_some_env_var_not_set_keep_going`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_use_command_specified_env_spec`
 - [ ] `anaconda_project/test/test_prepare.py::test_prepare_with_app_entry`
 - [ ] `anaconda_project/test/test_prepare.py::test_provide_whitelist`
 - [ ] `anaconda_project/test/test_prepare.py::test_unprepare_empty_directory`
 - [ ] `anaconda_project/test/test_prepare.py::test_unprepare_nothing_to_do`
 - [ ] `anaconda_project/test/test_prepare.py::test_update_environ`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_fails`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_fails_to_get_http_response`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_to_env_spec`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_which_already_exists`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_which_already_exists_with_fname`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_with_checksum`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_download_with_filename`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec_extending_existing_lists`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec_extending_existing_lists_with_versions`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec_no_global_platforms`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec_with_packages_and_channels`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_env_spec_with_real_conda_manager`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_packages_to_all_environments`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_platforms_already_exists`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_platforms_to_all_environments`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_service`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_service_already_exists`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_service_nondefault_variable_name`
 - [ ] `anaconda_project/test/test_project_ops.py::test_add_service_with_env_spec`
 - [ ] `anaconda_project/test/test_project_ops.py::test_clean`
 - [ ] `anaconda_project/test/test_project_ops.py::test_clean_environ_failed_delete`
 - [ ] `anaconda_project/test/test_project_ops.py::test_clean_failed_delete`
 - [ ] `anaconda_project/test/test_project_ops.py::test_clean_from_environ`
 - [ ] `anaconda_project/test/test_project_ops.py::test_lock_and_unlock_single_env`
 - [ ] `anaconda_project/test/test_project_ops.py::test_lock_and_update_and_unlock_all_envs`
 - [ ] `anaconda_project/test/test_project_ops.py::test_lock_conda_error`
 - [ ] `anaconda_project/test/test_project_ops.py::test_locking_with_missing_lock_set_does_an_update`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_download_with_prepare`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_packages_from_all_environments`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_packages_from_one_environment`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_packages_from_one_environment_leaving_others_unaffected`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_platforms_from_all_environments`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_platforms_from_one_environment`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_service_with_prepare`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_variables`
 - [ ] `anaconda_project/test/test_project_ops.py::test_remove_variables_with_env_spec`
 - [ ] `anaconda_project/test/test_project_ops.py::test_set_and_unset_variables_encrypted`
 - [ ] `anaconda_project/test/test_project_ops.py::test_set_and_unset_variables_some_encrypted`
 - [ ] `anaconda_project/test/test_project_ops.py::test_set_variables`
 - [ ] `anaconda_project/test/test_project_ops.py::test_set_variables_nonexistent`
 - [ ] `anaconda_project/test/test_project_ops.py::test_unlock_conda_error`
 - [ ] `anaconda_project/test/test_project_ops.py::test_unset_variables`
 - [ ] `anaconda_project/test/test_project_ops.py::test_update_empty_lock_sets`
 - [ ] `anaconda_project/test/test_project_ops.py::test_update_unlocked_envs`

**Comment by mcg1969** [comment]
We're not failing on conda canary anymore.
