### ISSUE TITLE
Creating specific Python version environment

### ISSUE THREAD

**Issue by msalvaris** [Anaconda-Platform/anaconda-project#132]
I have a project file where I define that I want the environment to be a python 3.6 env:
env_specs:
  default:
    description: Sets up a default python 3 environment
    packages:
    - python==3.6
    - scipy==0.19.1
    - scikit-learn==0.19.0
    - numpy==1.13.1

Whenever I run prepare it seems to install python as well as python 3.6. Below is the output from the prepare command with the verbose flag
mat@ms4deep:~/test_repos/deep_bait$ anaconda-project --verbose prepare
$ git ls-files --others --ignored --exclude-standard --directory
$ conda create --yes --quiet --prefix /home/mat/test_repos/deep_bait/envs/default numpy==1.13.1 anaconda python==3.6 jupyter ipython anaconda-project scipy==0.19.1 scikit-learn==0.19.0 python
$ /home/mat/test_repos/deep_bait/envs/default/bin/pip install --quiet --no-deps python-dotenv==0.7.1 nbconvert==5.1.1 ipykernel==4.6.1 Pillow==4.3.0 nbformat==4.4.0 azure-storage==0.33.0 toolz==0.8.2 requests==2.18.4 msrest==0.4.16 setuptools==36.5.0 fire==0.1.2

Now the order is not constant and if python comes before python==3.6 I end up with a Python 2.7 env. 

Is there a way to force constant order or eliminate the python installation?

Thanks in advance

**Comment by mcg1969** [comment]
This seems like a bug in conda, really. After all, `conda create -n test python python==3.6` and `conda create -n test python==3.6 python` arguably should work, and both do the same thing. And this seems to have been _fixed_ with conda as well.

Furthermore, I'm unable to see a duplicate `python` spec being added to the `conda` command during `anaconda-project --verbose prepare`.

I'm inclined therefore to close this, but if it needs to be re-opened, please do, with a more recent test case.
