### ISSUE TITLE
Proposal - Change output message of 'conda activate'

### ISSUE THREAD

**Issue by joshy** [Anaconda-Platform/anaconda-project#133]
Whenever I want to change to a different conda environment I can't remember the command to list all environments. Somehow my brain can't remember it. However I know I can activate it with `conda activate <env name>` once I know the name. 
When running just `conda activate` it tells me: `You need to specify a conda environment.` This is correct but also not very helpful. My suggestion would be to change the message to something like:
`You need to specify a conda environment. To list environments use "conda env list"`. Even better would be of course to just print out directly the installed environments. This would probably needs some work and would be doing to much. 

If you enter in Google "conda " the first entry is listing all environments, which suggests I am not the only one who can't remember the command.

Feel free to close it, if you don't agree.

**Comment by goanpeca** [comment]
You probably want to report this over https://github.com/conda/conda
