### ISSUE TITLE
Tests should not be reformatting the code

### ISSUE THREAD

**Issue by mcg1969** [Anaconda-Platform/anaconda-project#138]
Why does `scripts/run_tests.py` reformat the code using `yapf`? It seems to me that reformatting is for _readability_, and that is useless if the readable version of the code is never checked into the repo. 

Furthermore, because so much of the code needs reformatting, running the test script locally clutters up the local git staging. I ended up having to discard all of my changes and start fresh because I couldn't navigate between the yapf changes any my own.

I am _all for_ enforcing code formatting/style requirements in the repo itself. But that means the CI should enforce, not reformat.

Until this is fixed, please consider modifying CONTRIBUTING.md to warn people about this and recommend that they stage their changes before running any tests. This at least makes it somewhat easier to revert any reformatting changes so that they can be separate from the contributor's functional changes. I'm happy to add this paragraph to the docs myself.

**Comment by goanpeca** [comment]
@mcg1969 that is not how it works AFAIK. CI checks for code formatting, if there is a need for formatting it will fail the CI, so devs indeed need to run the formatting scripts when submitting a PR otherwise CI won't pass (unless they happen to write the code in the exact way yapf is expecting it to be...)

**Comment by mcg1969** [comment]
Something's wrong then, because I am seeing a _lot_ of reformatting occurring on a fresh branch with no modifications.

**Comment by mcg1969** [comment]
OK, I say that, but now I'm running it on master and it's not reformatting. I'll close this and re-open if I can figure out what happened.

**Comment by goanpeca** [comment]
@mcg1969 you need to use a specific version of YAPF I think.

https://github.com/Anaconda-Platform/anaconda-project/blob/master/.travis.yml#L77

**Comment by mcg1969** [comment]
Yes, that's probably it, thanks! I originally used the wrong version of yapf, but then I corrected it. I didn't appreciate that the previous version had left a bunch of its effects behind
