### ISSUE TITLE
add a third library to anaconda

### ISSUE THREAD

**Issue by TamouzeAssi** [Anaconda-Platform/anaconda-project#149]
Hello,

I installed anaconda and create my own virtual environment.

I have a third library `https://github.com/cemoody/lda2vec` i want to install it. 

inside this folder: https://github.com/cemoody/lda2vec there is file setup.py that permit to install it.

 how can add this library to my virtual environment.

what i did is executing pip install setup.py. so when i executing pip list i can see lda2vec in the list. Is it the best strategy to do this job?

**Comment by mcg1969** [comment]
I'm afraid this is the wrong issue page. This should likely go to
https://github.com/ContinuumIO/anaconda-issues/issues
