### ISSUE TITLE
Anaconda-project made available on PyPI, yet does not install

### ISSUE THREAD

**Issue by chrish42** [Anaconda-Platform/anaconda-project#153]
There is a wheel for Anaconda-project on PyPI, at https://pypi.org/project/anaconda-project/, except that it does not install with `pip install`:

```
anaconda-project
  Using cached https://files.pythonhosted.org/packages/3f/6b/986e3731d08cb840bd02fead7b3556d26402bae77475a4793ea3ceda46b5/anaconda_project-0.8.2-py2.py3-none-any.whl
Collecting tornado>=4.2 (from anaconda-project)
Collecting requests (from anaconda-project)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting anaconda-client (from anaconda-project)
  Using cached https://files.pythonhosted.org/packages/68/ca/a455502c16a912cba5d5513ebee4076f2a101cf8c036e5bf541f1b201b2b/anaconda-client-1.2.2.tar.gz
Collecting ruamel-yaml (from anaconda-project)
  Could not find a version that satisfies the requirement ruamel-yaml (from anaconda-project) (from versions: )
No matching distribution found for ruamel-yaml (from anaconda-project)
```

**Comment by mcg1969** [comment]
Thanks for the note about this (and sorry for the incredible delay here). I'm not convinced we should be even bothering to deliver this package on PyPi, as it is so dependent upon conda for proper function.

**Comment by chrish42** [comment]
Sure. If it's possible to remove it from PyPI, then that could also be a solution. Pretty much anything is better than leaving a broken package. If I hadn't found it on PyPI, I would likely have tried via Conda...

**Comment by mcg1969** [comment]
@goanpeca, do you think we could remove anaconda-project from PyPi? Given its dependence upon conda I really think we might as well distribute it exclusively through conda. And I suspect it's out of date there. (I'm asking you because you're the owner of the PyPi package.)

**Comment by goanpeca** [comment]
@mcg1969 sure, I can do that, but maybe it is better I transfer the ownership to someone over Anaconda?

I will need emails for the pypi users that want to be added as owners

**Comment by mcg1969** [comment]
You can add me (mcg1969) and I can take care of the rest... thanks!

**Comment by goanpeca** [comment]
Done @mcg1969!. It seems you will need to remove me (I cannot remove myself)

<img width="1048" alt="Screen Shot 2019-07-03 at 00 02 51" src="https://user-images.githubusercontent.com/3627835/60564613-f453e380-9d25-11e9-852f-1e965101d722.png">

**Comment by mcg1969** [comment]
Thank you @goanpeca !

**Comment by mcg1969** [comment]
I've removed the package from PyPi. Given that conda is a _requirement_, it seems reasonable.
