### ISSUE TITLE
Using pip with git in anaconda-project.yml

### ISSUE THREAD

**Issue by npavlovikj** [Anaconda-Platform/anaconda-project#172]
Hi,

In my environment, I am installing few Python packages from Git. When I install them manually I do, for example, "**pip install git+https://github.com/jupyterhub/wrapspawner.git**". However, if I have:
**packages:
  -pip:
    -git+https://github.com/jupyterhub/wrapspawner.git**
in "**anaconda-project.yml**", I am getting "**anaconda-project.yml: invalid pip package specifier: git+https://github.com/jupyterhub/wrapspawner.git**" error.

Is it possible to install Python packages from Git using anaconda-project, and if so, what is the proper syntax I can use?

Thank you,
Natasha

**Comment by cpbotha** [comment]
I just tested this with the current 0.8.2 anaconda-project, and it seems to work. (I have a `git+` requirement of django_mailbox in the `- pip:` section: `- git+https://github.com/coddingtonbear/django-mailbox.git@26786a0b3200515d490ecb69e1bc5b86efcc0ffb#egg=django-mailbox`

```
$ ~/miniconda3/bin/anaconda-project --verbose prepare
$ git ls-files --others --ignored --exclude-standard --directory
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip --version
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip list
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip --version
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip list
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip --version
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip list
$ /Users/cpbotha/Dropbox/work/code/aikno/envs/default/bin/pip install --quiet --no-deps celery django>=2 django-celery-beat django-celery-results django-debug-toolbar git+https://github.com/coddingtonbear/django-mailbox.git@26786a0b3200515d490ecb69e1bc5b86efcc0ffb#egg=django-mailbox django-sendfile djangorestframework gevent html2text psycopg2 pycountry pypdf2 pytest-cov pytest-django python-magic redis textract
$ conda info --json
The project is ready to run commands.
Use `anaconda-project list-commands` to see what's available.
```

**Comment by jlstevens** [comment]
I can confirm this works but only if you keep the `#egg=...` syntax at the end (pip alone doesn't seem to require this). 

This does seem to be very useful functionality, especially for development purposes. Is this documented anywhere at the moment?

**Comment by AlbertDeFusco** [comment]
This is now fixed and docs improved
