### ISSUE TITLE
Python Installation Not Working

### ISSUE THREAD

**Issue by RealFlamin** [Anaconda-Platform/anaconda-project#174]
![image](https://user-images.githubusercontent.com/46260139/50546590-e495fe00-0c21-11e9-98ae-53a1a5784a60.png)
Every time I try to download python, it comes up with an error message. It says "Corrupted Installer." I don't know why this is happening really. I tried to download it on my external hard drive, but that's all that comes up. It was for a python course and I told them about it and they told me to report it here. Is there any way you can fix this? Thank you.

**Comment by mcg1969** [comment]
You've posted this to the wrong issue tracker. Please report this to https://github.com/ContinuumIO/anaconda-issues
