### ISSUE TITLE
conda: error: argument command: invalid choice: '/home/user/anaconda3/bin/conda' when trying to update, upgrade or install

### ISSUE THREAD

**Issue by thebeancounter** [Anaconda-Platform/anaconda-project#175]
I am having some packages issues and need to upgrade python packages, 

I try to run 
conda update --all 

but getting the above error. 

I found [this](https://github.com/ContinuumIO/anaconda-issues/issues/6171) issue - stating the solution is 
```
$ conda update anaconda-navigator
$ conda update navigator-updater
```

But when I try to use the solution i keep getting the same error 

I also tried 

`conda update anconda` 

same error 

I tried adding -c conda-forge to all of the commands without any change. 

I am using ubuntu 18 latest and updated

**Comment by mcg1969** [comment]
I think you posted this to the wrong repo. This looks like something to go into the conda issue tracker.
