### ISSUE TITLE
Anaconda Installation Error 

### ISSUE THREAD

**Issue by parakhchauhan** [Anaconda-Platform/anaconda-project#180]
![2018-12-17_05-29-16-687b6982da31ed384315165aca2902d7](https://user-images.githubusercontent.com/35947199/52135707-625b8800-266c-11e9-96fc-5d6fbb946fe4.png)

**Comment by mcg1969** [comment]
This is the wrong forum for these issues; please submit them here: https://github.com/ContinuumIO/anaconda-issues/issues
