### ISSUE TITLE
anaconda-project list-packages excludes pip packages

### ISSUE THREAD

**Issue by cpbotha** [Anaconda-Platform/anaconda-project#181]
This is probably related to https://github.com/Anaconda-Platform/anaconda-project/issues/151 -- `anaconda-project list-packages` only lists conda packages, no pip packages that are specified in the `pip:` subsection of `packages:`.

I just confirmed this behaviour with latest master of anaconda-project.

Having first class support for pip packages would make anaconda-project a super serious Python project and package management tool, surpassing poetry and pipenv in terms of capabilities.

**Comment by mcg1969** [comment]
@cpbotha I'm grateful to have someone like you putting this tool through its paces. I have a keen interest to see this mature. Is there any chance you could help us with some pull requests? I'll take a look at this when I can but the more hands on keys the better.

**Comment by leudom** [comment]
@cpbotha Are there any news regarding that feature?

**Comment by cpbotha** [comment]
I'm sorry folks, I could not continue working on this.

In the meantime, for package pinning we have been using poetry where possible, and conda-pack otherwise.

**Comment by michaelschufi** [comment]
Hi @cpbotha 
So what's currently the best solution? Running poetry or pipenv would create a different environment, right? And locking dependencies with some different tool that installs it, doesn't really lock it, correct?

**Comment by AlbertDeFusco** [comment]
I think I'll have some time soon to work on this.

Let me confirm that you'd like the anaconda-project-lock.yml file to include the full pip package list.

I can also work on listing declared pip packages with list-packages

**Comment by michaelschufi** [comment]
I think having the info in the file makes most sense. My use cases involving lock files are:
- Running CI/CD pipelines that should install the exact same versions for all the dependencies (and sub*-dependencies) given the same commit. (`npm ci` command as an example)
- If such a command is not available: To look manually what versions were installed in order to debug errors and making old repos run again.

**Comment by AlbertDeFusco** [comment]
See #317 for the work-in-progress. It's not too far from completion, just want to add `remove-packages --pip ...` and finalize the tests.

**Comment by AlbertDeFusco** [comment]
to everyone here #317 is very near to being merged. If you're willing I'd appreciate it if you might test it to make sure I haven't missed anything important

```
conda install -c defusco/label/dev anaconda-project=0.9.1+116
```

**Comment by AlbertDeFusco** [comment]
Specifically @cpbotha, this development version of anaconda-project (0.9.1+117 above) includes the ability to "conda-pack" envs directly into the archive that you may be interested in.

```
anaconda-project archive --pack-envs /path/to/archive.[zip/tar.gz/tar.bz2]
```

https://anaconda-project.readthedocs.io/en/latest/user-guide/tasks/create-project-archive.html#experimental-packaging-environments

**Comment by AlbertDeFusco** [comment]
PR #317 is now merged and ready for the next release
