### ISSUE TITLE
Allow "dependencies" as an alias for "packages"?

### ISSUE THREAD

**Issue by jbednar** [Anaconda-Platform/anaconda-project#194]
Am anaconda-project.yml file includes nearly the same information as in a Conda environment.yml file, while also adding other metadata like commands and datasets to run.  I personally find an anaconda-project.yml file to be a useful way to capture all of that information, but sometimes I only want to create the conda environment, without using any of the other info. Given that there are far more conda users than anaconda-project users, it's useful to be able to manually create a conda environment with conda commands rather than the ones specific to anaconda-project. 

Julia Signell has made examples of achieving this, such as for the [bay_trimesh](https://github.com/pyviz-topics/examples/tree/master/bay_trimesh) PyViz demo. Specifically, she used YAML references to create a "packages" field in the .yml file that refers to the list declared in the "dependencies" field:

```
dependencies: &deps
  - python=3.6
  - notebook ==5.7.8

packages: *deps
```

Having done so, the .yml file now works with conda as if it were an environment.yml file:

```
conda env create --file anaconda-project.yml
```

That's great and already works, but it's mysterious to readers, annoying to have to do, and currently generates a warning about anaconda-project not understanding the "packages" field.  It would be nice if anaconda-project could follow conda syntax and accept `dependencies` as an alias for `packages`, and indeed to suggest that people generally use `dependencies` so that their files will just automatically work with conda as-is.

This is another example of unifying the .yml syntax with what conda accepts more generally, such as already proposed in https://github.com/Anaconda-Platform/anaconda-project/issues/193.

**Comment by mcg1969** [comment]
Addressed by #200
