### ISSUE TITLE
'activate virtual environment' make so many output message

### ISSUE THREAD

**Issue by nchos88** [Anaconda-Platform/anaconda-project#197]
When i activate virtual environment, so many output message appear in command line.

And message appear only in specific environment. (see ## output message)

---------------------------------------
**Here is explaination.** 

I had 3 virtual environment. gb ( message appear environment ) , h2o , tf2 

(1) message of gb
(2) message of h2o 
(3) message of h2o and tf2 after activate gb 
(4) message of tf2 

**(2)**
C:\Users\TBI>activate h2o
C:\Users\TBI>conda.bat activate h2o
(h2o) C:\Users\TBI>

**(3)**
(gb) C:\Users\TBI>conda.bat activate h2o
C:\Users\TBI>set "KERAS_BACKEND="
(h2o) C:\Users\TBI>

(gb) C:\Users\TBI>conda.bat activate tf2
C:\Users\TBI>set "KERAS_BACKEND="
(tf2) C:\Users\TBI>

**(4)** 
(h2o) C:\Users\TBI>activate tf2
(h2o) C:\Users\TBI>conda.bat activate tf2
---

os : windows 10 
conda version : 4.6.14

**(1)**
## output message
![image](https://user-images.githubusercontent.com/36718545/58234500-a2f52380-7d79-11e9-8a44-7790bd96c6f0.png)

--- 
(tf2) C:\Users\TBI>activate gb

(tf2) C:\Users\TBI>conda.bat activate gb

C:\Users\TBI>python C:\Users\TBI\Miniconda3\envs\gb\etc\keras\load_config.py  1>temp.txt

C:\Users\TBI>set /p KERAS_BACKEND= 0<temp.txt

C:\Users\TBI>del temp.txt

C:\Users\TBI>python -c "import keras"  1>nul 2>&1

C:\Users\TBI>if errorlevel 1 (
ver  1>nul
 set "KERAS_BACKEND=theano"
 python -c "import keras"  1>nul 2>&1
)

C:\Users\TBI>SET DISTUTILS_USE_SDK=1

C:\Users\TBI>SET MSSdk=1

C:\Users\TBI>SET platform=

C:\Users\TBI>IF /I [AMD64] == [amd64] set "platform=true"

C:\Users\TBI>IF /I [] == [amd64] set "platform=true"

C:\Users\TBI>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )

C:\Users\TBI>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"

C:\Users\TBI>SET "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\"

C:\Users\TBI>if "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\" == "" (set "VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\" )

C:\Users\TBI>if "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\" == "" (
ECHO "Did not find VS in registry or in VS140COMNTOOLS env var - exiting"
 exit 1
)

C:\Users\TBI>echo "Found VS2014 at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\"
"Found VS2014 at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\"

C:\Users\TBI>SET "VS_VERSION=14.0"

C:\Users\TBI>SET "VS_MAJOR=14"

C:\Users\TBI>SET "VS_YEAR=2015"

C:\Users\TBI>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

C:\Users\TBI>set "MSYS2_ENV_CONV_EXCL=CL"

C:\Users\TBI>set "PY_VCRUNTIME_REDIST=\vcruntime140.dll"

C:\Users\TBI>set "CFLAGS= -MD -GL"

C:\Users\TBI>set "CXXFLAGS= -MD -GL"

C:\Users\TBI>set "LDFLAGS_SHARED= -LTCG ucrt.lib"

C:\Users\TBI>IF /I [] == [win-64] (set "folder=x64" )  else (set "folder=x86" )

C:\Users\TBI>for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\*1*" /B /O:N') do for %A in (%~I) do if "%A" == "8.1" set win=%A

C:\Users\TBI>for %A in (10) do if "%A" == "8.1" set win=%A

C:\Users\TBI>if "10" == "8.1" set win=10

C:\Users\TBI>for %A in (8.1) do if "%A" == "8.1" set win=%A

C:\Users\TBI>if "8.1" == "8.1" set win=8.1

C:\Users\TBI>for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\*1*" /B /O:N') do for %A in (%~I) do if "%A" == "10" set win=%A

C:\Users\TBI>for %A in (10) do if "%A" == "10" set win=%A

C:\Users\TBI>if "10" == "10" set win=10

C:\Users\TBI>for %A in (8.1) do if "%A" == "10" set win=%A

C:\Users\TBI>if "8.1" == "10" set win=8.1

C:\Users\TBI>setlocal enabledelayedexpansion

C:\Users\TBI>if "10" == "10" (
for /F "tokens=*" %I in ('dir "C:\Program Files (x86)\Windows Kits\10\bin\10*" /B /O:N') do for %A in (%~I) do set last=%A
 set "sdk_bin_path=C:\Program Files (x86)\Windows Kits\10\bin\!last!\x86"
)  else (set "sdk_bin_path=C:\Program Files (x86)\Windows Kits\8.1\bin\x86" )

C:\Users\TBI>for %A in (10.0.14393.0) do set last=%A

C:\Users\TBI>set last=10.0.14393.0

C:\Users\TBI>for %A in (10.0.15063.0) do set last=%A

C:\Users\TBI>set last=10.0.15063.0

C:\Users\TBI>for %A in (10.0.16299.0) do set last=%A

C:\Users\TBI>set last=10.0.16299.0

C:\Users\TBI>for %A in (10.0.17134.0) do set last=%A

C:\Users\TBI>set last=10.0.17134.0

C:\Users\TBI>endlocal   & set "PATH=C:\Users\TBI\Miniconda3\envs\gb;C:\Users\TBI\Miniconda3\envs\gb\Library\mingw-w64\bin;C:\Users\TBI\Miniconda3\envs\gb\Library\usr\bin;C:\Users\TBI\Miniconda3\envs\gb\Library\bin;C:\Users\TBI\Miniconda3\envs\gb\Scripts;C:\Users\TBI\Miniconda3\envs\gb\bin;C:\Users\TBI\Miniconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ASAP\ASAP190\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\TBI\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files\Git\cmd;C:\Program Files\PuTTY;C:\Program Files (x86)\Skype\Phone;C:\Android;C:\openslide\openslide-win64-20171122\bin;C:\bazel;C:\PATH;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\CMake\bin;C:\openslide-win64-20171122\openslide-win64-20171122\bin;C:\Users\TBI\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\TortoiseGit\bin;C:\webcrowser_driver;C:\Users\TBI\AppData\Local\Julia-1.1.0\bin;C:\julia\Judy-master;.;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git LFS;C:\Program Files\nodejs;C:\Users\TBI\Miniconda3;C:\Users\TBI\Miniconda3\Library\mingw-w64\bin;C:\Users\TBI\Miniconda3\Library\usr\bin;C:\Users\TBI\Miniconda3\Library\bin;C:\Users\TBI\Miniconda3\Scripts;C:\Users\TBI\AppData\Local\Microsoft\WindowsApps;C:\Users\TBI\AppData\Local\GitHubDesktop\bin;C:\openslide\openslide-win64-20171122\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\TBI\AppData\Local\atom\bin;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Users\TBI\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64;C:\Users\TBI\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Docker Toolbox;C:\Users\TBI\AppData\Local\Pandoc;C:\Users\TBI\AppData\Roaming\npm;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x86"

C:\Users\TBI>SET "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"

C:\Users\TBI>CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\..\..\VC\vcvarsall.bat" amd64

(gb) C:\Users\TBI>

---------
---------

**Package List**
**(gb)**
(gb) C:\Users\TBI>conda list
# packages in environment at C:\Users\TBI\Miniconda3\envs\gb:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.7.1                    py36_0    conda-forge
appdirs                   1.4.3                    pypi_0    pypi
astor                     0.7.1                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bayesian-optimization     1.0.1                    pypi_0    pypi
black                     19.3b0                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.16.3               h6538335_0    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
catboost                  0.13.1                   py36_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
colorama                  0.4.1                      py_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
feather-format            0.4.0                    pypi_0    pypi
freetype                  2.10.0               h5db478b_0    conda-forge
future                    0.17.1                   pypi_0    pypi
gast                      0.2.2                      py_0    conda-forge
grpcio                    1.12.1           py36h1a1b453_0
h5py                      2.9.0           nompi_py36h3cb27cb_1102    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.3                      203
ipykernel                 5.1.0           py36h39e3cac_1002    conda-forge
ipython                   7.4.0            py36h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.13.3                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      8d                       vc14_2
jsonschema                3.0.1                    py36_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.1.6                    py36_0    conda-forge
keras-applications        1.0.7                      py_0    conda-forge
keras-preprocessing       1.0.9                      py_0    conda-forge
kiwisolver                1.0.1           py36he980bc4_1002    conda-forge
libblas                   3.8.0                     4_mkl    conda-forge
libcblas                  3.8.0                     4_mkl    conda-forge
libgpuarray               0.7.6             hfa6e2cd_1003    conda-forge
liblapack                 3.8.0                     4_mkl    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libprotobuf               3.7.0                h1a1b453_2    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
libtiff                   4.0.6                    vc14_2
lightgbm                  2.2.4                    pypi_0    pypi
llvmlite                  0.24.0                   py36_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
matplotlib                3.0.3                    py36_0    conda-forge
matplotlib-base           3.0.3            py36h3e3dc42_0    conda-forge
missingno                 0.4.1                    pypi_0    pypi
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.1                      144
mock                      2.0.0                 py36_1001    conda-forge
msgpack                   0.6.1                    pypi_0    pypi
msgpack-numpy             0.4.4.2                  pypi_0    pypi
msys2-conda-epoch         20160418                      1
nb_conda                  2.2.1                    py36_2    conda-forge
nb_conda_kernels          2.2.1                    py36_0    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
notebook                  5.7.8                    py36_0    conda-forge
numba                     0.39.0           py36h830ac7b_0
numexpr                   2.6.9           py36h6538335_1000    conda-forge
numpy                     1.16.2           py36h8078771_1    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pandas                    0.24.2           py36h6538335_0    conda-forge
pandoc                    2.7.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.4                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pbr                       5.1.3                      py_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    6.0.0                    pypi_0    pypi
pip                       19.0.3                   py36_0    conda-forge
plotly                    3.9.0                    pypi_0    pypi
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.0            py36he025d50_0    conda-forge
pyarrow                   0.13.0                   pypi_0    pypi
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6           py36h452e1ab_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pypdf2                    1.26.0                   pypi_0    pypi
pyqt                      4.11.4                   py36_2    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pyrsistent                0.14.11          py36hfa6e2cd_0    conda-forge
pytables                  3.5.1            py36hb9ab341_1    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywinpty                  0.5.5                 py36_1000    conda-forge
pyyaml                    5.1              py36hfa6e2cd_0    conda-forge
pyzmq                     18.0.1           py36he418aac_0    conda-forge
qt                        4.8.7                    vc14_6
requests                  2.21.0                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scikit-learn              0.21.1           py36h0ff8352_0    conda-forge
scipy                     1.2.1            py36h29ff71c_0
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.12.0                py36_1000    conda-forge
statsmodels               0.9.0           py36hfa6e2cd_1000    conda-forge
tabulate                  0.8.3                    pypi_0    pypi
tensorboard               1.10.0                   pypi_0    pypi
tensorflow                1.13.1          gpu_py36h9006a92_0
tensorflow-base           1.13.1          gpu_py36h871c8ca_0
tensorflow-estimator      1.13.0           py36h39e3cac_0    conda-forge
tensorflow-gpu            1.13.1               h0d30ee6_0
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
theano                    1.0.4           py36h6538335_1000    conda-forge
toml                      0.10.0                   pypi_0    pypi
tornado                   6.0.2            py36hfa6e2cd_0    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
umap-learn                0.3.8                    py36_0    conda-forge
urllib3                   1.24.1                   pypi_0    pypi
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
vs2015_win-64             14.0.25123           h17c34da_3    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.15.2                     py_0    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
xgboost                   0.83.dev0                pypi_0    pypi
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.2.5             he025d50_1006    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge

**(h2o)**
(h2o) C:\Users\TBI>conda list
# packages in environment at C:\Users\TBI\Miniconda3\envs\h2o:
#
# Name                    Version                   Build  Channel
certifi                   2019.3.9                 py36_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.1                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
h2o                       3.24.0.3                 pypi_0    pypi
idna                      2.8                      pypi_0    pypi
intel-openmp              2019.3                      203
libblas                   3.8.0                     9_mkl    conda-forge
libcblas                  3.8.0                     9_mkl    conda-forge
liblapack                 3.8.0                     9_mkl    conda-forge
mkl                       2019.3                      203
numpy                     1.16.3           py36h873a0b8_0    conda-forge
pandas                    0.24.2           py36h6538335_0    conda-forge
pip                       19.1.1                   py36_0    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
requests                  2.21.0                   pypi_0    pypi
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
tabulate                  0.8.3                    pypi_0    pypi
urllib3                   1.24.3                   pypi_0    pypi
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge

**(tf2)**
(tf2) C:\Users\TBI>conda list
# packages in environment at C:\Users\TBI\Miniconda3\envs\tf2:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
astor                     0.7.1                    pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.1.6                    pypi_0    pypi
grpcio                    1.20.1                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.1                     vc14_0    conda-forge
intel-openmp              2019.3                      203
ipykernel                 5.1.0           py37h39e3cac_1002    conda-forge
ipython                   7.5.0            py37h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.1.0            py37he980bc4_0    conda-forge
libblas                   3.8.0                     9_mkl    conda-forge
libcblas                  3.8.0                     9_mkl    conda-forge
liblapack                 3.8.0                     9_mkl    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
llvmlite                  0.28.0                   py37_0    conda-forge
markdown                  3.1                      pypi_0    pypi
matplotlib                3.0.3                    py37_1    conda-forge
matplotlib-base           3.0.3            py37h3e3dc42_1    conda-forge
mkl                       2019.3                      203
numba                     0.43.1           py37hf9181ef_0
numpy                     1.16.3           py37h873a0b8_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pandas                    0.24.2           py37h6538335_0    conda-forge
parso                     0.4.0                      py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.1.1                   py37_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.1                    pypi_0    pypi
pygments                  2.4.0                      py_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py37h6538335_0    conda-forge
python                    3.7.3                hb12ca83_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyzmq                     18.0.1           py37he7828b0_1    conda-forge
qt                        5.9.7                hc6833c9_1    conda-forge
scikit-learn              0.20.3           py37h3d241f0_1    conda-forge
scipy                     1.2.1            py37h29ff71c_0
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.12.0                   pypi_0    pypi
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
tb-nightly                1.14.0a20190301          pypi_0    pypi
tensorflow-gpu            2.0.0a0                  pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tf-estimator-nightly      1.14.0.dev2019030115          pypi_0    pypi
tornado                   6.0.2            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
umap-learn                0.3.8                    py37_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                      py_1    conda-forge
werkzeug                  0.15.2                   pypi_0    pypi
wheel                     0.33.4                   py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
zeromq                    4.3.1             he025d50_1000    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge

**Comment by mcg1969** [comment]
I'm afraid you've posted this in the wrong place. This is for the very specific `anaconda-project` repo, not a general Anaconda issues tracker.
