### ISSUE TITLE
Using Pyinstaller with Anaconda 3.7.3 needs PyQt5 even if not imported in code

### ISSUE THREAD

**Issue by skbobade** [Anaconda-Platform/anaconda-project#207]
I am writing a test code with Python and tested that it works on both Python 3.7 and 3.7.3 
The code uses tkinter, and does not use PyQT5
I use pyinstaller 3.4 I convert the python to exe.

With the same code and and same dependencies (including version number) - while converting code to exe using pyinstaller 3.4, with Python 3.7.3 - Pyinstaller asks for additional imports related to PyQt5 (and maybe more). This causes executable to expand in size with unwanted dependencies bundled in output. 

Doing same thing with Python 3.7 removes the issue. 
Not sure if this is Anaconda specific or general Python issue. 

Both tests were done in virtual environment with Anaconda Python 3.7.3 as base.
Attached logs from pyinstaller for both versions.

[withpy3.7.3.txt](https://github.com/Anaconda-Platform/anaconda-project/files/3333380/withpy3.7.3.txt)
[withpy3.7.txt](https://github.com/Anaconda-Platform/anaconda-project/files/3333381/withpy3.7.txt)

**Comment by zooba** [comment]
FYI, I just closed the same report on the [CPython issue tracker](https://bugs.python.org/issue37425).

This is because matplotlib tries to import Qt, succeeds in one test environment and not the other, and pyinstaller decides that it needs to be included.

You'll have to report this to pyinstaller.

**Comment by skbobade** [comment]
PyQt5 was installed when trying to make exe with Python 3.7.3 because without it pyinstaller will fail to produce output if PyQt5 is absent. 

I'll recreate log with python 3.7.3 with PyQt5 removed. 

This issue was not reported to Pyinstaller since same version (3.4) was used.

**Comment by skbobade** [comment]
Added log without PyQt5 & Python 3.7.3 which fails to produce output.
Maybe this is issue of Matplotlib then? Not sure if versions are changed between the distribution.

[withpy3.7.3 -without PyQt5.txt](https://github.com/Anaconda-Platform/anaconda-project/files/3335685/withpy3.7.3.-without.PyQt5.txt)

**Comment by mcg1969** [comment]
I'm afraid this is the wrong issue tracker. This is for a very specific software package, not Anaconda in general.
