### ISSUE TITLE
Mac Catalina

### ISSUE THREAD

**Issue by manuelcosta74** [Anaconda-Platform/anaconda-project#211]
After updating Mac OS to Catalina (beta 3), Anaconda stopped working and we can see the following error raised when terminal is used to open Anaconda-Navigator.app : "failed with error -10810"

Note: did try to change "System Preferences"->"Security & Privacy" to "Allow apps downloaded from" : "Anywhere" and result is the same

**Comment by mcg1969** [comment]
I'm afraid this is the wrong issue tracker; perhaps you mean [this one](https://github.com/ContinuumIO/anaconda-issues)? This is not for general Anaconda questions.
