### ISSUE TITLE
conda update fails with error: "ERROR conda.core.link:_execute(637): An error occurred while installing package 'None'."

### ISSUE THREAD

**Issue by ebo** [Anaconda-Platform/anaconda-project#212]
I recently updated an old anaconda install and it gave me the following results:

=========================
## Package Plan ##

  environment location: /home/ebo/anaconda3

The following NEW packages will be INSTALLED:

  blosc              pkgs/main/linux-64::blosc-1.16.3-hd408876_0
  dbus               pkgs/main/linux-64::dbus-1.13.6-h746ee38_0
  defusedxml         pkgs/main/noarch::defusedxml-0.6.0-py_0
  hdf5               pkgs/main/linux-64::hdf5-1.10.4-hb1b8bf9_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2019.4-243
  joblib             pkgs/main/linux-64::joblib-0.13.2-py37_0
  libcurl            pkgs/main/linux-64::libcurl-7.64.1-h20c2e04_0
  liblief            pkgs/main/linux-64::liblief-0.9.0-h7725739_2
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libssh2            pkgs/main/linux-64::libssh2-1.8.2-h1ba5d50_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libtiff            pkgs/main/linux-64::libtiff-4.0.10-h2733197_2
  libxslt            pkgs/main/linux-64::libxslt-1.1.33-h7d1a2b0_0
  mkl                pkgs/main/linux-64::mkl-2019.4-243
  mock               pkgs/main/linux-64::mock-3.0.5-py37_0
  pcre               pkgs/main/linux-64::pcre-8.43-he6710b0_0
  soupsieve          pkgs/main/linux-64::soupsieve-1.8-py37_0
  sphinxcontrib-app~ pkgs/main/noarch::sphinxcontrib-applehelp-1.0.1-py_0
  sphinxcontrib-dev~ pkgs/main/noarch::sphinxcontrib-devhelp-1.0.1-py_0
  sphinxcontrib-htm~ pkgs/main/noarch::sphinxcontrib-htmlhelp-1.0.2-py_0
  sphinxcontrib-jsm~ pkgs/main/noarch::sphinxcontrib-jsmath-1.0.1-py_0
  sphinxcontrib-qth~ pkgs/main/noarch::sphinxcontrib-qthelp-1.0.2-py_0
  sphinxcontrib-ser~ pkgs/main/noarch::sphinxcontrib-serializinghtml-1.1.3-py_0
  zeromq             pkgs/main/linux-64::zeromq-4.3.1-he6710b0_3
  zipp               pkgs/main/noarch::zipp-0.5.1-py_0

The following packages will be UPDATED:

  anaconda-navigator                           1.9.6-py36_0 --> 1.9.7-py37_0
  conda-build                                 3.17.6-py36_0 --> 3.17.8-py37_0

The following packages will be DOWNGRADED:

  _ipyw_jlab_nb_ext~                           0.1.0-py36_0 --> 0.1.0-py37_0
  conda                                        4.7.5-py37_0 --> 4.6.14-py37_0
  navigator-updater                            0.2.1-py36_0 --> 0.2.1-py37_0

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(637): An error occurred while installing package 'None'.
AssertionError()
Attempting to roll back.

Rolling back transaction: done

AssertionError()
()
========================

And from here on out I cannot update anaconda or move forward.  I will cache this installation and reinstall from scratch with the latest release.  Any ideas on what caused this and how to avoid it in the future would be appreciated.

**Comment by mcg1969** [comment]
I'm afraid this is the wrong issue tracker; perhaps you mean [this one](https://github.com/ContinuumIO/anaconda-issues)? This is not for general Anaconda questions.
