### ISSUE TITLE
_ssl.pyd in Anaconda 3.7.3 causing pip install error

### ISSUE THREAD

**Issue by krissdap** [Anaconda-Platform/anaconda-project#218]
Hi,

First, thanks for having created and maintaining Anaconda, it's been a great tool.

Now to my question, I have found an odd case with Anaconda's Python 3.7.3 on Windows 10 Pro, which I've been using Anaconda's Python 3.6.X for a long time with no problem.

Then I just created a new env in 3.7.3 that I cannot `pip install` anything, keep getting this error.
`WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.`

After digging around I found that if I replaced `DLLs/_ssl.pyd` of this environment with one from official (non anaconda) Python 3.7.3, then everything works.

Another test I came to while trying to pinpoint the root cause, is by running `import _ssl` command which will give different results.

```
>>> import _ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

But if replaced the `_ssl.pyd` file, with one from official distribution, the import will success.

The original _ssl.pyd file (with error):
size: 114,176 bytes
md5sum: e0fb051af25ea21a45641341f1424808

One from original distribution (no error):
size: 123,408 bytes
md5sum: a3c9649e68206c25eff2d09a0bd323f0

Tested system:
Windows 10 Pro (version 1809, build 17763.615)

So far the workaround does not cause any negative effects, but I'd be good to know if there's any mis-configuration on my side.
So if there's any suggestions where I should look, that'd be great.

Thanks.

**Comment by mcg1969** [comment]
This is the wrong issue tracker I'm afraid; I think you're looking for this:
- https://github.com/ContinuumIO/anaconda-issues

**Comment by krissdap** [comment]
Ha! My bad :)

Thanks @mcg1969
