### ISSUE TITLE
ugly formatting of packages list in default anaconda-project.yml

### ISSUE THREAD

**Issue by havocp** [Anaconda-Platform/anaconda-project#22]
If you `anaconda-project init` in an empty directory, we should really use the multiline 
```
packages:
  - anaconda
```
instead of
```
packages: [anaconda]
```

But, haven't figured out yet how to convince ruamel.yaml to do this.

**Comment by goanpeca** [comment]
@havocp normal pyyaml handles this in an easy way, so maybe we will need to create that part of the file with normal pyyaml and append to it? I agree it looks weird to have the `[package, package2]` format

**Comment by havocp** [comment]
have a pr already :-) had to go exploring in the ruamel source (and had to install mercurial to do it, yikes)

**Comment by goanpeca** [comment]
>and had to install mercurial to do it, yikes

XD
