### ISSUE TITLE
Throw fewer warnings

### ISSUE THREAD

**Issue by jsignell** [Anaconda-Platform/anaconda-project#221]
Since I am declaring some extra fields on anaconda-project.yml in the projects on https://github.com/pyviz-topics/examples, I get some warnings whenever I run them. The projects run just fine and simply skip over missing fields. So I don't think they should throw an error.

```
Potential issues with this project:
  * anaconda-project.yml: Unknown field name 'maintainers'
  * anaconda-project.yml: Unknown field name 'labels'
```

Alternatively, there could be a special metadata field that I could store arbitrary data in.

**Comment by jbednar** [comment]
Or there could be a supported field where you list the other fields explicitly:

```
user_fields: 
  - maintainers
  - labels
```

That way you could still get error reporting in the case of misspellings and directives not supported by this version of the code, while allowing arbitrary metadata to be added by users.

**Comment by jsignell** [comment]
Right that was what I was trying to suggest metadata could be.

**Comment by jbednar** [comment]
I understood you to be proposing something different, i.e. a single top-level "metadata" field that users could put arbitrary subfields into.  My proposal (not saying whether it is better or worse) is different, which is to allow the user to declare an arbitrary number of allowed top-level fields in which they can safely put their data.  I.e., the full example would be:

```
user_fields: 
  - maintainers
  - labels

maintainers:
  - jsignell
  
labels:
  - approved: True
```

**Comment by mcg1969** [comment]
Closing because I think #224 / #228 handles this
