### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by jsignell** [Anaconda-Platform/anaconda-project#225]
I think the name `anaconda-project` is pretty bad for several reasons:
 1. too long
 2. implies some affiliation with the company (scares away OSS users)
 3. has a dash in it

I'd like to open this issue to discuss some other names that might be a better fit.

## conda-make

PROS:
  - analogous to conda-build
  - gets away from company affiliation 
  - people know what `make` does

CONS:
  - has dash in it
  - `conda-make run notebook` doesn't make much sense in english

## project

PROS:
   - `project run notebook` makes sense in english
   - gets away from company affiliation
   - similar to original

CONS:
   - possibly confusing given the geographic implication of the word `project`
   - also project as in display using a projector. Basically project as a verb might be confusing

## conda-project OR conda project

PROS:
   - `conda project run notebook` makes sense in english
   - gets away from company affiliation
   - very similar to original
   - analogous to conda-build, conda-env, conda-pack ... 

CONS:
   - overloading conda?
   - conda-project has a dash in it and is still pretty long

**Comment by bollwyvl** [comment]
kapsel 🙉

**Comment by mcg1969** [comment]
This isn't ever going to be `conda project`. They're going in a different but similar direction.

I'm open to another name but of course we'll have to keep `anaconda-project` around for back compatibility.

**Comment by jbednar** [comment]
I don't think we should change the name if we're planning to move to functionality provided by conda itself, for our own purposes...
