### ISSUE TITLE
how to reinstall the missing packages iin anaconda 

### ISSUE THREAD

**Issue by isalirezag** [Anaconda-Platform/anaconda-project#241]
I am using anaconda on ubuntu 16.04 for a couple of years now.
I messed up some of my libraries and had to remove some packages, and during that process a lot packages has been removed.
now i fix the issue but my anaconda is missing a lot of packages...
e.g. when I open spyder it shows me error `AttributeError: module 'matplotlib' has no attribute 'interactive'`

My question:
is there a way to update/reinstall the packages that are missing from anaconda? I mean comparing the the default anaconda.
i did `conda update conda` and `conda update --all`, but nothing happened...

**Comment by jbednar** [comment]
I'll close this issue as issues on this repo are meant to be about the `anaconda-project` library, not the Anaconda distribution itself.

That said, you may be able to install the anaconda metapackage to restore those packages; see https://www.anaconda.com/whats-in-a-name-clarifying-the-anaconda-metapackage/  
But you should probably instead be making a new environment starting from the Anaconda distribution and adding the ones that you want, as it's often difficult to install the metapackage into an environment that already contains a bunch of packages that the metapackage might conflict with.  Also note that the Spyder message above does not indicate that any package is missing; it looks like a version mismatch, to me.
