### ISSUE TITLE
Packages installed when none requested by project

### ISSUE THREAD

**Issue by jlstevens** [Anaconda-Platform/anaconda-project#252]
When running a simple test project without any package dependencies declared, I noticed that conda downloads and installs a large number of dependencies even though none are requested.

Steps to reproduce (tested on OSX and Windows 10):

1. `anaconda-project init`
2. `anaconda-project run`

On OSX, 473 unnecessary python packages were downloaded and installed (I don't think it is worth listing them all here). There is nothing in the `anaconda-project.yml` to indicate that the commands even require Python.

**Comment by jbednar** [comment]
What gets installed when you add one, zero-dependency package?

If it's just that one package, indicating that zero requested packages is a special case, can you find the bit in the source code that handles the zero-package case?  Maybe what happens in that case is described in the comments there.

**Comment by jlstevens** [comment]
@jbednar The `anaconda-project add-packages` command seems to consistently add `anaconda` as a package which can includes a lot more than necessary. However, if I edit the `anaconda-project.yml` manually (after `anaconda-project init` and `anaconda-project add-packages param`) to remove the `anaconda` package:

```yml
packages:
- param
```

Then the set of packages installed is much more reasonable:

```
The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2019.11.27-0
  certifi            pkgs/main/osx-64::certifi-2019.11.28-py38_0
  libcxx             pkgs/main/osx-64::libcxx-4.0.1-hcfea43d_1
  libcxxabi          pkgs/main/osx-64::libcxxabi-4.0.1-hcfea43d_1
  libedit            pkgs/main/osx-64::libedit-3.1.20181209-hb402a30_0
  libffi             pkgs/main/osx-64::libffi-3.2.1-h475c297_4
  ncurses            pkgs/main/osx-64::ncurses-6.1-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1d-h1de35cc_3
  param              pkgs/main/noarch::param-1.9.2-py_0
  pip                pkgs/main/osx-64::pip-20.0.2-py38_0
  python             pkgs/main/osx-64::python-3.8.1-h359304d_1
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-45.1.0-py38_0
  sqlite             pkgs/main/osx-64::sqlite-3.30.1-ha441bb4_0
  tk                 pkgs/main/osx-64::tk-8.6.8-ha441bb4_0
  wheel              pkgs/main/osx-64::wheel-0.33.6-py38_0
  xz                 pkgs/main/osx-64::xz-5.2.4-h1de35cc_4
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3
```

**Comment by jlstevens** [comment]
The fact that both the empty specification and the minimal specification (a single, pure python package) either implicitly installs anaconda (former case) or adds it to the package list suggest that `anaconda-project` is assuming `- anaconda` as a default across python projects.

I'm not convinced this is good behavior: even though `anaconda` is a great base for all sorts of work, I think the user should *choose* to add `anaconda` as a package in order to avoid installing unnecessary dependencies. For one thing, conda solves much faster when fewer packages are involved.

**Comment by jlstevens** [comment]
It is also a little odd that both `- anaconda` and `- param` get added to the package list given that 1) conda is being invoked to solve the specification and 2) `param` is already included in `anaconda`!

**Comment by AlbertDeFusco** [comment]
See issue #148 for previous discussion. Are getting different behavior?

**Comment by AlbertDeFusco** [comment]
I think this is already solved with. Maybe it could be default behavior?

```
> anaconda-project init --empty-environment
```

**Comment by AlbertDeFusco** [comment]
fixed
