### ISSUE TITLE
Anaconda project 0.8.4 reports its version as 0.8.3

### ISSUE THREAD

**Issue by jlstevens** [Anaconda-Platform/anaconda-project#254]
Likely to be an extremely easy fix but I think it is worth filing an issue in case anyone else gets confused by this.

To reproduce:

```bash
$ conda create -n example python
$ conda activate example
$ conda install anaconda-project=0.8.4 # 0.8.4 then lists as downloaded
$ anaconda-project --version
0.8.3
```

**Comment by AlbertDeFusco** [comment]
I believe this is fixed on master. Here's the output from my dev environment where I did `pip install -e`

```
>anaconda-project --version
v0.8.4+55.g19821ac
```

**Comment by sanbales** [comment]
Is this a duplicate of https://github.com/Anaconda-Platform/anaconda-project/issues/238?

**Comment by mcg1969** [comment]
It is indeed.
