### ISSUE TITLE
Feature request-adding environment variables directly into the environment.yaml file

### ISSUE THREAD

**Issue by theultimate1** [Anaconda-Platform/anaconda-project#262]
This is a feature request for having environment variables as part of the environment.yml file. It would be very helpful. An example of what I am talking about is attached in the file below.
[Feature request sample.txt](https://github.com/Anaconda-Platform/anaconda-project/files/4442978/Feature.request.sample.txt)
This would help a lot as right now I need to write a script to set all the environment variables(long one) and when sharing environment details, this easily becomes a hassle.Any work is appreciated.

**Comment by bkreider** [comment]
I think this is a duplicate issue in the conda issue tracker here: https://github.com/conda/conda/issues/9821

If you are intending this for anaconda-project, then you can already specify environment variables, but they are (i think) only used when a command is run in the project.  

(If i closed this in error, feel free to reopen).
