### ISSUE TITLE
Anaconda fails to install package

### ISSUE THREAD

**Issue by pranavagande** [Anaconda-Platform/anaconda-project#266]
I'm trying to install the [shogun-ml](https://www.shogun-toolbox.org/install#binaries) library using anaconda, but the following error shows up.

The command i'm using is: conda install -c conda-forge shogun

![image](https://user-images.githubusercontent.com/64346806/81895133-2f25d980-95cf-11ea-8f83-e72f183143c9.png)

**Comment by jbednar** [comment]
anaconda-project and conda are separate libraries, and here you appear to be using conda, not anaconda-project, so I'll close this and you can file an issue on https://github.com/conda/conda/issues instead.
