### ISSUE TITLE
Require project file to have a "name" field

### ISSUE THREAD

**Issue by havocp** [Anaconda-Platform/anaconda-project#27]
Right now a missing name field isn't an error, we use the directory name for the name in that case.
But since we're on a campaign to say that everything has to be explicitly in the project file, perhaps
we should require the name field. `anaconda-project init` would default to using the directory name for the name, probably. Right now `anaconda-project init` sets empty string for the name which causes us to fall back to the directory name, or something, this is kinda weird.

**Comment by goanpeca** [comment]
>But since we're on a campaign to say that everything has to be explicitly in the project file, perhaps
we should require the name field. anaconda-project init would default to using the directory name for the name, probably.

Me like!
