### ISSUE TITLE
unable to change virtual environment from navigator - ubuntu

### ISSUE THREAD

**Issue by jhachandan1994** [Anaconda-Platform/anaconda-project#271]
when anaconda is launched through bash command anaconda-navigator or desktop application anaconda navigator. if i change the environment from home page of navigator and then launch jupyter notebook the notebook gets started in root environment always. I am observing this issue in ubuntu only windows and mac versions are working properly.

Steps to Reproduce
1. open terminal and then type anaconda-navigator or start anaconda navigator from applications menu
2. after navigator opens select a environment from dropdown list.
3. launch jupyter notebook and try to import any package installed in the virtual env.

After changing the environment from anaconda navigator gui and launching jupyter notebook from anaconda navigator gui the notebook should open in selected environment rather then root environment.

**Comment by mcg1969** [comment]
I'm afraid you have the wrong issue tracker—this is specifically for the anaconda-project Python package.
