### ISSUE TITLE
Wrong access rights of jupyter*exe in scripts

### ISSUE THREAD

**Issue by Bummibaer** [Anaconda-Platform/anaconda-project#273]
Under Windows 10 The Exe-Files in the scripts-Folder get 
LogonSessionID_0_xxxxxxxxxxx User rights
not the 
current user
I.E. I cannot start jupyter-lab.exe
Please change.

**Comment by jbednar** [comment]
I'm not sure what you're asking; what scripts folder?  Maybe you are talking about something other than anaconda-project?

**Comment by mcg1969** [comment]
Indeed, this is not an anaconda-project issue.
