### ISSUE TITLE
conflict with libraries in implicit directories

### ISSUE THREAD

**Issue by tbhaxor** [Anaconda-Platform/anaconda-project#281]
I am using Manjaro OS with anaconda latest version (just installed). I want to compile [Yet Another Magic Lamp](https://aur.archlinux.org/packages/kwin-effects-yet-another-magic-lamp/) effect. 

On executing `cmake`, I am getting the following warning.

```
CMake Warning at src/CMakeLists.txt:37 (add_library):
  Cannot generate a safe runtime search path for target
  kwin4_effect_yetanothermagiclamp because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libQt5Xml.so.5] in /usr/lib may be hidden by files in:
      /home/terabyte/anaconda3/lib
    runtime library [libQt5Widgets.so.5] in /usr/lib may be hidden by files in:
      /home/terabyte/anaconda3/lib

  Some of these libraries may not be found correctly.


CMake Warning at src/kcm/CMakeLists.txt:15 (add_library):
  Cannot generate a safe runtime search path for target
  kwin_yetanothermagiclamp_config because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libQt5Xml.so.5] in /usr/lib may be hidden by files in:
      /home/terabyte/anaconda3/lib
    runtime library [libQt5Widgets.so.5] in /usr/lib may be hidden by files in:
      /home/terabyte/anaconda3/lib

  Some of these libraries may not be found correctly.
```
The magic lamp effect is behaving abnormally with this. Please help me

**Comment by tbhaxor** [comment]
According to the owner of this repo, it should be built with the QT libraries of the system, please see this link https://github.com/zzag/kwin-effects-yet-another-magic-lamp/issues/27#issuecomment-663406109. 

Please help me in this

**Comment by jbednar** [comment]
Closing as this does not appear to be an issue with the anaconda-project command; this is not a site for general programming issues.

**Comment by tbhaxor** [comment]
@jbednar Where i can ask this question then?

**Comment by jbednar** [comment]
You'd have to find someone who knows about magic lamps, I guess! :-) Definitely not me, in any case.
