### ISSUE TITLE
Anaconda Linux Installation Website Page

### ISSUE THREAD

**Issue by woosal1337** [Anaconda-Platform/anaconda-project#287]
On the linux installation on Anaconda, here, https://docs.anaconda.com/anaconda/install/linux/
please update **bash ~/Downloads/Anaconda3-2020.02-Linux-x86_64.sh**
to                     **bash ~/Downloads/Anaconda3-2020.07-Linux-x86_64.sh**

**Comment by jbednar** [comment]
This is the repository for the anaconda-project command, whereas you are reporting issues with the Anaconda Distribution or its docs.  See https://github.com/ContinuumIO/anaconda-issues for Distribution-related issues.
