### ISSUE TITLE
Anaconda Navigator Linux Installation Setup Error

### ISSUE THREAD

**Issue by woosal1337** [Anaconda-Platform/anaconda-project#288]
There is an issue with the **anaconda-navigator** as soon as it is installed as it does not open. However, after the full installation, and using the last step **source ~/.bashrc**, it is required to update the **anaconda-navigator** with 
**conda update anaconda-navigator**
after which it starts working. 
Please consider updating it at the end so it starts working without any issues.

**Comment by jbednar** [comment]
This is the repository for the anaconda-project command, whereas you are reporting issues with the Anaconda Distribution or its docs.  See https://github.com/ContinuumIO/anaconda-issues for Distribution-related issues.
