### ISSUE TITLE
Anaconda install tf-agents[reverb]

### ISSUE THREAD

**Issue by lamhoson** [Anaconda-Platform/anaconda-project#290]
Which version of anaconda can install tf-agents[reverb] ?

**Comment by jbednar** [comment]
Any anaconda version will provide conda, and so all anaconda versions are equally capable of installing any software available as a conda package. So the question is whether tf-agents has a conda package available, which you can search at anaconda.org.  This repo is about a separate library called anaconda-project, and is not a general location for help with conda.
