### ISSUE TITLE
[Feature Request] ARM64 Builds

### ISSUE THREAD

**Issue by fonnesbeck** [Anaconda-Platform/anaconda-project#291]
Given the increased prevalence of ARM hardware, it would be great to have ARM64 builds. I'm personally interested in running this on Windows and Linux, but with the M1 chips now available this is relevant for all 3 major platforms. Is this on the roadmap?

**Comment by jbednar** [comment]
Yes, I think it is, but this is the github repo for the `anaconda-project` command, which is separate from conda and the Anaconda Distribution. anaconda-project helps you make self-contained, reproducible projects using Conda.

**Comment by fonnesbeck** [comment]
Sorry about that!
