### ISSUE TITLE
Impossible to launch Anaconda-Navigator

### ISSUE THREAD

**Issue by Jacques2101** [Anaconda-Platform/anaconda-project#304]
hi, 
It seems that there is a bug with anaconda-navigator. 
To reproduce it, I : 
- add Conda-forge as a channel
- update all in base environment with `conda update --all` which create a lot of update 

After that it becomes impossible to launch anaconda-navigator. 
I receive no error message. I tried all the debug process that was describe in "troubleshooting" page but noway. Still not working. 

It seems that inside Conda-forge there is an update that creates problem to Anaconda-navigator. After that I need to reinstall Anaconda. 

I am on macOS Big Sur. 
Thx for your help.

**Comment by jbednar** [comment]
anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" in general. See https://github.com/ContinuumIO/anaconda-issues .
