### ISSUE TITLE
[BUG] Anaconda is broken and does not work on Ubuntu 20.04.2 LTS (Focal Fossa)

### ISSUE THREAD

**Issue by pbower** [Anaconda-Platform/anaconda-project#316]
#### A fresh Anaconda Environment should work without the following:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 

(This solving environment remains for 10 minutes+).

Anaconda is rendered unusable.

#### Relevant configuration files

# Complete, minimal, self-contained example code that reproduces the issue

1. rm -rf ~/anaconda3 (or the equivalent miniconda3 directory). 
2. Remove local environment variables if needed.
3. Download either Miniconda or Anaconda for Python 3, Linux from the anaconda website.
4. Follow the recommended setup instructions as listed here: https://docs.anaconda.com/anaconda/install/linux/

____________________________________________________________________________________________________
Installation
For x86 systems.

In your browser, download the Anaconda installer for Linux.

RECOMMENDED: Verify data integrity with SHA-256. For more information on hashes, see What about cryptographic hash verification?

Open a terminal and run the following:

sha256sum /path/filename
Enter the following to install Anaconda for Python 3.7:

bash ~/Downloads/Anaconda3-2020.02-Linux-x86_64.sh
OR Enter the following to install Anaconda for Python 2.7:

bash ~/Downloads/Anaconda2-2019.10-Linux-x86_64.sh
Note

Include the bash command regardless of whether or not you are using Bash shell.

Note

If you did not download to your Downloads directory, replace ~/Downloads/ with the path to the file you downloaded.

The installer prompts “In order to continue the installation process, please review the license agreement.” Click Enter to view license terms.

Scroll to the bottom of the license terms and enter “Yes” to agree.

The installer prompts you to click Enter to accept the default install location, CTRL-C to cancel the installation, or specify an alternate installation directory. If you accept the default install location, the installer displays “PREFIX=/home/<user>/anaconda<2 or 3>” and continues the installation. It may take a few minutes to complete.

Note

We recommend you accept the default install location. Do not choose the path as /usr for the Anaconda/Miniconda installation.

The installer prompts “Do you wish the installer to initialize Anaconda3 by running conda init?” We recommend “yes”.

Note

If you enter “no”, then conda will not modify your shell scripts at all. In order to initialize after the installation process is done, first run source <path to conda>/bin/activate and then run conda init. See FAQ.

The installer finishes and displays “Thank you for installing Anaconda<2 or 3>!”

The installer provides a link to install PyCharm for Anaconda at https://www.anaconda.com/pycharm.

Close and open your terminal window for the installation to take effect, or you can enter the command source ~/.bashrc.

To control whether or not each shell session has the base environment activated or not, run conda config --set auto_activate_base False or True. To run conda from anywhere without having the base environment activated by default, use conda config --set auto_activate_base False. This only works if you have run conda init first.

Note

conda init is available in conda versions 4.6.12 and later.

Verify your installation.

Note

If you install multiple versions of Anaconda, the system defaults to the most current version as long as you haven’t altered the default install path.

**Comment by jbednar** [comment]
anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" in general. For  issues with the Anaconda Distribution, see. https://github.com/ContinuumIO/anaconda-issues .
