### ISSUE TITLE
Allow one to use `--override-channels` for reproducibility.

### ISSUE THREAD

**Issue by mforbes** [Anaconda-Platform/anaconda-project#336]
Since the goal of `anaconda-project` is reproducibility, would it not make sense that `--override-channels` be allowed so that channels are specified precisely in `anaconda-project.yml` and not sullied by global config files?  It seems that perhaps this should even be the default behavior.

I am running into a problem on [CoCalc](https://cocalc.com/) where I am trying to use `anaconda-project` to initialize an environment.  The problem is that the base `conda` environment has a `.condarc` with a large list of channels such that `anaconda-project prepare` runs out of memory (limited to 1GB by default for small projects).  I have the same issue with `conda env create` which is thwarted by the inability of this command to accept `--override-channels` (I am using `pip` packages too, so `conda env create` is kind of needed):

* [Override Channels with `conda env create` #10498](https://github.com/conda/conda/issues/10498): No way to use `--override channels` with `conda env create`.
* [Add support for channel and solver arguments to conda env create #9065 ](https://github.com/conda/conda/issues/9065) 

Briefly looking at the code, it seems that it would be pretty easy to add the `--override-channels` flag so that the channels can be completely (and reproducibly) specified in the `anaconda-project.yaml` file.  This would allow `anaconda-project` to bypass these conda issues providing a more reproducible alternative to `conda env create`.

**Comment by AlbertDeFusco** [comment]
I see, good catch. I've got a streamlined Conda invocation in #352 where I think we can include this fix and tests as well.

**Comment by AlbertDeFusco** [comment]
This is fixed by #352
