### ISSUE TITLE
latest miniconda3 aarch64 install error

### ISSUE THREAD

**Issue by QGB** [Anaconda-Platform/anaconda-project#338]
Do you accept the license terms? [yes|no]
[no] >>> yes

Miniconda3 will now be installed into this location:
/data/data/com.termux/files/home/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/data/data/com.termux/files/home/miniconda3] >>>
PREFIX=/data/data/com.termux/files/home/miniconda3
Unpacking payload ...
./Miniconda3-latest-Linux-aarch64.sh: 390: ./Miniconda3-latest-Linux-aarch64.sh: /data/data/com.termux/files/home/miniconda3/conda.exe: not found
./Miniconda3-latest-Linux-aarch64.sh: 392: ./Miniconda3-latest-Linux-aarch64.sh: /data/data/com.termux/files/home/miniconda3/conda.exe: not found
$

**Comment by jbednar** [comment]
anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" in general. Please see https://github.com/ContinuumIO/anaconda-issues instead.
