### ISSUE TITLE
Jupyterlab logo doesn't appear any more

### ISSUE THREAD

**Issue by mrexito** [Anaconda-Platform/anaconda-project#348]
I've updated Jupyterlab to the version 3.2.4 and since then I don't see any more this application on my Anaconda Navigator. I have to launch Jupyterlab from the terminal.

#### ALL software version info
![image](https://user-images.githubusercontent.com/51750327/145580618-ed11d85d-f950-4bf8-a093-f0913de5a663.png)

#### Description of expected behavior and the observed behavior
I should see the Jupyterlab logo to start the application
#### Relevant configuration files

```

# list of commands you executed
conda install -c conda-forge jupyterlab=3.2.4
```

**Comment by jbednar** [comment]
This repository is for the command `anaconda-project`, while your bug report appears to be about Anaconda Navigator. You can try: https://github.com/ContinuumIO/anaconda-issues
