### ISSUE TITLE
[BUG] `anaconda-project prepare` doesn't recognize `osx-arm64` platform

### ISSUE THREAD

**Issue by mattkram** [Anaconda-Platform/anaconda-project#382]
#### ALL software version info

```shell
$ conda --version
conda 4.12.0
```

```shell
$ anaconda-project --version
0.10.2
```

Mac OS 12.1

#### Description of expected behavior and the observed behavior

`anaconda-project` doesn't recognize M1 packages for `osx-arm64` platform.

#### Relevant configuration files

```yaml
name: bug
packages:
- python=3.8
platforms:
- osx-arm64
```

# Complete, minimal, self-contained example code that reproduces the issue

```
anaconda-project prepare
```

#### Command output and/or screenshots of the bug in action
```
Potential issues with this project:
  * anaconda-project.yml: Unusual platform name 'osx-arm64' may be a typo (more usual examples: linux-64, osx-64, win-64)
```

**Comment by AlbertDeFusco** [comment]
fixed by #352
