### ISSUE TITLE
How do I compile dlib (with compile options  -O3 and -mavx) for use in anaconda?

### ISSUE THREAD

**Issue by martinenkoEduard** [Anaconda-Platform/anaconda-project#385]
How do I compile dlib (with compile options  -O3 and -mavx) for use in anaconda?
Is there a guide? 
I get an abhorent performance with default  that installed with dlib.

**Comment by jbednar** [comment]
This repository is for the `anaconda-project` command, not for general help with conda.  See https://docs.conda.io/en/latest/help-support.html for conda resources.
