### ISSUE TITLE
[ENH] Implicit "defaults" channel

### ISSUE THREAD

**Issue by AlbertDeFusco** [Anaconda-Platform/anaconda-project#387]
Starting in version 0.11.0 condarc "channels:" list is ignored. 

* If a project yaml does not have any "channels:" listed it is now unusable.
* Some project yaml files have "channels:" but would implicitly rely on "defaults"
    * in an unspecified/tested/studied order

Proposal:
* always use "defaults" with and without explicit channel lists
* implement Conda env create's "nodefaults": https://github.dev/conda/conda/blob/9bf4c1721da4d44739546109a78fb2edb40af95b/conda_env/installers/conda.py#L19
* if "defaults" is not listed in the ordered-list of channels it will go **????**

Goal:
* ensure some backward compatibility while still not relying on condarc state

**Comment by AlbertDeFusco** [comment]
@jbednar  and @jlstevens where should `defaults` go when not supplied in `channels` and when `nodefaults` is not also specified? First or last?

**Comment by jbednar** [comment]
I vote for implementing`nodefaults` and for otherwise assuming `defaults` is in the list.

> @jbednar and @jlstevens where should defaults go when not supplied in channels and when nodefaults is not also specified? First or last?

Wherever anaconda-project  behaves as it did before. Did it previously act like it was implicitly first, or implicitly last?

**Comment by jlstevens** [comment]
I will confirm it for myself but I believe it was implicitly last (as Albert mentioned above).

**Comment by AlbertDeFusco** [comment]
merged and released in 0.11.1
