### ISSUE TITLE
How to find the library owned by which package?

### ISSUE THREAD

**Issue by jayramr** [Anaconda-Platform/anaconda-project#390]
Hi All,

My IT flagged a vulnerability on a specific library under one environment on anaconda. And they are advising me to update the below file to the latest version.

```
/opt/conda/envs/test_env/lib/jrt-fs.jar
```

But here, the above file created by some package, but I'm not sure which package it is? Please help me to figure how can i find the exact package/component owning this path /opt/conda/envs/test_env/lib/jrt-fs.jar. So i can go to that specific component and update the fix

Thanks
Jay

**Comment by jbednar** [comment]
This is the repo for the `anaconda-project` command, not for conda or Anaconda in general. That said, you should be able to run `grep jrt-fs.jar /opt/conda/envs/test_env/conda-meta/*.json` to see which package lists that file in its manifest.
