### ISSUE TITLE
[BUG] "Failed to initialize Anaconda directories": can't install Anaconda on Windows

### ISSUE THREAD

**Issue by throwable-one** [Anaconda-Platform/anaconda-project#391]
Windows10 (21H2). 
Anaconda3-2022.10-Windows-x86_64.

Install for: Just Me (Recommended). Path (default): ``C:\Users\%USERNAME%\anaconda3``.

Result:
Failed to initialize Anaconda directories
<img width="379" alt="conda_fail" src="https://user-images.githubusercontent.com/7673963/199080266-f70370a8-5836-4214-8adc-ec5adece4998.png">

**Comment by throwable-one** [comment]
From debug view
[20396] failed to get the Python codec of the filesystem encoding****

**Comment by throwable-one** [comment]
Actually, the problem was a directory with junk chars in name inside of my home directory, which probably led to the problem described above.  

Issue could be closed, but still could be useful for anyone who face the same problem

**Comment by jbednar** [comment]
Closing as this was an issue with installing the Anaconda distribution, not an issue with the anaconda-project command.
