### ISSUE TITLE
small typo in docs when adding notebook to project

### ISSUE THREAD

**Issue by lukereding** [Anaconda-Platform/anaconda-project#57]
There seems to be a small typo in the docs for anaconda project's tutorial ([in github](https://github.com/Anaconda-Platform/anaconda-project/blob/master/docs/source/tutorial.rst#additional-information) or [in the docs](http://anaconda-project.readthedocs.io/en/latest/tutorial.html#additional-information)). 

Running

```
anaconda-project add-command mynotebook.ipynb
```

in a directory with `mynotebook.ipynb` results in 

```
$ anaconda-project add-command my_notebook.ipynb 
usage: anaconda-project add-command [-h] [--directory PROJECT_DIR]
                                    [--type {unix,windows,notebook,bokeh_app,ask}]
                                    [--env-spec ENVIRONMENT_SPEC_NAME]
                                    [--supports-http-options]
                                    [--no-supports-http-options]
                                    NAME COMMAND
anaconda-project add-command: error: the following arguments are required: COMMAND
```
So I think the command just needs to be changed to something like

```
anaconda-project add-command mynotebook.ipynb run_notebook
```
which works fine

```
$ anaconda-project add-command my_notebook.ipynb run_notebook
Is `my_notebook.ipynb` a (B)okeh app, (N)otebook, or (C)ommand line? n
Added a command 'my_notebook.ipynb' to the project. Run it with `anaconda-project run my_notebook.ipynb`.

$ anaconda-project list-commands
Commands for project: /Users/lreding/Documents/test

Name               Description
====               ===========
my_notebook.ipynb  Notebook run_notebook
```

**Comment by allardbrain** [comment]
Hi @lukereding, I just looked into this (I'm a first time contributor). The GitHub link you supplied returns a 404 message, and the docs link somehow is not sending me to the correct page. Happy to try to make the edit you suggested if you're able to confirm where the typo is. Thanks!

**Comment by allardbrain** [comment]
Actually, upon further digging this appears to have been [fixed](http://anaconda-project.readthedocs.io/en/latest/user-guide/tasks/work-with-commands.html) already.

**Comment by fpliger** [comment]
thanks @allardbrain for stepping. It is indeed closed :)

Let me know if you want to contribute and what kind of issues/fixes you'd bee happy to point you in the right direction. (yeah, the ones with `tag:help-wanted` are a good start, if you find any that fits)
