### ISSUE TITLE
[DOCS] In example Pandas listed in prose but not in code snippet

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-project#69]
RTD "Getting Started" section here: http://anaconda-project.readthedocs.io/en/latest/getting-started.html

states that "bokeh, pandas, numpy, scikit-learn need to be specified" but then the example YAML snippet does not include Pandas.

**Comment by ijstokes** [comment]
https://github.com/Anaconda-Platform/anaconda-project/blame/master/docs/source/getting-started.rst#L31-L39

**Comment by allardbrain** [comment]
Hi @ijstokes, I just looked into this but I don't see the language about "bokeh, pandas, numpy, scikit-learn need to be specified" in the webpage / file that you linked to. Happy to fix this if you can confirm where the omission is. Thanks!

**Comment by fpliger** [comment]
this seems to have been fixed
