### ISSUE TITLE
[QUESTION] Can I specify that a project is only for one platform?

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-project#72]
I am working on an Anaconda Project that I **know** will only run on a Mac.  Is there some way for me to specify that so it is either visible to someone who is considering running my project **or** (even better) can be picked up automatically by `anaconda-project run` which will then do a sanity check and if the platform where `run` is invoked doesn't match the one for which the project was written it will complain loudly and exit.

If that feature doesn't exist, does it make sense to rename this from a question to a feature enhancement?

**Comment by ijstokes** [comment]
Further to this: platform details could be useful (RHEL vs. Debian, or even RHEL 6 vs RHEL 7).

**Comment by havocp** [comment]
In 0.6.0 and above (only available in the dev label right this moment), there is a `platforms:` field.
It may (not 100% sure) be ignored if you haven't locked the project though, a possible enhancement would be to enforce it even when unlocked. The valid platform names are the same ones as for conda, minus noarch, so linux-64, osx-64 and so on.

**Comment by havocp** [comment]
Done
