### ISSUE TITLE
[ENH] run sub-command should provide some status output unless --quiet

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-project#73]
I have done `anaconda-project run` about a hundred times in the past few days (mostly in the past 12 hours), and I'm realizing that I'd like to know what the `run` sub-command is up to (or even what the `anaconda-project` command is up to, since I suppose there may be some pre-staging before `run` sub-command starts?

Since the `run` command is prepared to spit stuff out at the screen, including some interactive terminal/readline queries (e.g. for setting variables), it does not seem unreasonable for it to also, by default, give some updates on what it is doing.

Unless a `--quiet` flag is passed in, which should make it be *very* quiet (like silent, I'd say).

**Comment by havocp** [comment]
There's a general need for progress indication / what's going on, this is intended to be captured in #14

**Comment by havocp** [comment]
I think with latest code this should be a lot better.
