### ISSUE TITLE
add-download stalls

### ISSUE THREAD

**Issue by lukereding** [Anaconda-Platform/anaconda-project#74]
I'm having trouble using the `anaconda-project add-download` command:

```
$ mkdir test && cd test

$ anaconda-project init
Project configuration is in /Users/lreding/Desktop/test/anaconda-project.yml

$ anaconda-project --verbose add-download IRIS_CSV https://raw.githubusercontent.com/bokeh/bokeh/f9aa6a8caae8c7c12efd32be95ec7b0216f62203/bokeh/sampledata/iris.csv
conda create --yes --quiet --prefix /Users/lreding/Desktop/test/envs/default python anaconda
```
I've let it run at this point for > half an hour and nothing more happens.

There doesn't seem to be an issue with the link to the data:

```
$ wget https://raw.githubusercontent.com/bokeh/bokeh/f9aa6a8caae8c7c12efd32be95ec7b0216f62203/bokeh/sampledata/iris.csv
--2017-05-18 10:05:42--  https://raw.githubusercontent.com/bokeh/bokeh/f9aa6a8caae8c7c12efd32be95ec7b0216f62203/bokeh/sampledata/iris.csv
Resolving raw.githubusercontent.com... 151.101.48.133
Connecting to raw.githubusercontent.com|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3858 (3.8K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[=================>]   3.77K  --.-KB/s    in 0s      

2017-05-18 10:05:42 (65.7 MB/s) - ‘iris.csv’ saved [3858/3858]


$ echo $?
0

```

Some more info:

```
$ anaconda-project --version
0.4.1

$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/lreding/anaconda3  (writable)
    default environment : /Users/lreding/anaconda3
       envs directories : /Users/lreding/anaconda3/envs
          package cache : /Users/lreding/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/lreding/.condarc
           offline mode : False
```

The same thing seems to be happening using the [Anaconda3 docker image](https://hub.docker.com/r/continuumio/anaconda3/).

ping @havocp

**Comment by havocp** [comment]
It looks like the thing taking forever is the "conda create"; you can take the download out of the equation by doing `anaconda-project prepare` before you add the download, and if conda create is the problem, the `anaconda-project prepare` should also hang for a long time. #14 will of course make this less confusing.

You can check whether anything is happening by seeing if the envs/ directory is growing, on Linux for example and maybe mac you could do `ls -1R envs | wc -l` to count how many files are in `envs`, run that while things are stuck and see if files are being created.

Another debug possibility is to cut-and-paste that `conda create` command that `--verbose` prints out and try running it by hand, maybe minus the `--quiet --yes` options, to see if it succeeds.

**Comment by lukereding** [comment]
`anaconda-project prepare` is also hanging for a long time as you predicted.

Running the `conda create` command looks like

```
$ conda create --prefix /Users/lreding/Desktop/test/envs/default python anaconda
Fetching package metadata ...........
Solving package specifications: .......
```
...and then it hangs here indefinitely.

Running ` ls -1R envs | wc -l` results in

```
ls: envs: No such file or directory
       0
```

**Comment by havocp** [comment]
If you can reproduce with the plain conda command, I'd propose we move this issue over to the conda repo.
