### ISSUE TITLE
Make license type explicit in file headers and brand change

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Platform/anaconda-project#95]
We should be explicit about the license type.

Currently it looks like:

```python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Copyright © 2016, Continuum Analytics, Inc. All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
# ----------------------------------------------------------------------------
```

We should have something like:
```python
# -----------------------------------------------------------------------------
# Copyright (c) 2017, Continuum Analytics, Inc.
#
# Licensed under the terms of the BSD 3 Clause License
# The full license is in the file LICENSE.txt, distributed with this software.
# -----------------------------------------------------------------------------
```

**Comment by havocp** [comment]
Might want to check with legal and see if there's a formal policy on this. I believe it's incorrect to change all files to 2017, if they haven't been touched in 2017. Though I haven't been very good about adding 2017 to the files that were touched, unfortunately.

**Comment by goanpeca** [comment]
@havocp actually we use can use a range, my point was more about the `Licensed under the terms of the BSD 3 Clause License` than the year ;-)
