### ISSUE TITLE
Create a RELEASE.md file with steps to perform pypi and conda release

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Platform/anaconda-project#97]

**Comment by havocp** [comment]
It should probably say "run build_and_upload.sh" and not much else (though i guess there's one extra step with conda, set the label to main instead of dev)

**Comment by goanpeca** [comment]
>It should probably say "run build_and_upload.sh" and not much else (though i guess there's one extra step with conda, set the label to main instead of dev)

Sure ;-), will make that :-p

**Comment by goanpeca** [comment]
Also we need to upload to pypi, and describe what the different scripts do, now that they are (will soon be) split and outside of the setup.py
